<center> <img src='https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png'/></center>
<center><h2>Best NumPy Functions For Data Science </h2></center>

NumPy stands for numerical python and is a library in python that adds the functionality of large multi-dimensional arrays and matrices. It works as a building block for all the libraries in pydata ecosystem. NumPy is one of the most useful tools for a data scientist that uses python. It can handle large-size data efficiently. One of the biggest reasons to use NumPy is its arrays and multiple scientific functions to work with arrays.

#### **========𝗧𝗔𝗕𝗟𝗘 𝗢𝗙 𝗖𝗢𝗡𝗧𝗘𝗡𝗧========**
- Array Creation Methods
- Array Operations
- Replacing Values Inside Array
- Set Operations
- Splitting
- Stacking
- Comparing Two Arrays
- Repeating Array Elements
- Einstein Summation Conventions
- Statistical Analysis
- Array Printing Options
- Save and Load Array Data

# Array Creation Methods

## 1. Array
It is used to create one-dimensional or multidimensional arrays from scratch.<br>
`array(Object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)`


**Important params**<br>
`dtype`: desired data type for the resultant array.<br>
`ndim`: Specify the minimum number of dimensions for the resultant array.

In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

You can also use this function to convert series or dataframes into a NumPy array.

In [2]:
import pandas as pd
sex = pd.Series(['Male','Male','Female'])
np.array(sex)

array(['Male', 'Male', 'Female'], dtype=object)

### 2. Linspace
Creates an array with evenly spaced float numbers over a specified interval.<br>
`np.linspace(start, stop, num = 50, endpoint=True, retstep=False, dtype=None,axis=0)`

**Important params**<br>
`start`: starting index<br>
`end`: last index<br>
`num`: number of samples to generate, default = 50.

In [3]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 3. Arange
Return evenly spaced integer values over a given interval with some step size.<br>
`np.arrange(star, stop, step, dtype=None)`

**Important params**<br>
`step`: Space between values.

In [4]:
np.arange(5,10,2)

array([5, 7, 9])

### 4. Uniform Samples
Generate a random sample from a uniform distribution between lower and higher limit values.<br>
`np.uniform(low=0.0, high=1.0, size=None)`

In [5]:
np.random.uniform(5,10,size = 4)

array([6.00853088, 9.5556225 , 8.86445095, 9.10203602])

In [6]:
np.random.uniform(size = 5)

array([0.98655491, 0.3975531 , 0.58043242, 0.56045157, 0.2353161 ])

In [7]:
np.random.uniform(size = (2,3))

array([[0.28319731, 0.37270475, 0.94530465],
       [0.16921795, 0.74366046, 0.86850734]])

### 5. Random.randint
Generate n random integer samples within a range.<br>
`np.random.randiant(low, high=None, size=None, dtype=int)`

In [8]:
np.random.randint(5,10,10)

array([6, 8, 9, 8, 6, 6, 5, 7, 6, 7], dtype=int32)

### 6. Random.random
Generate n random float samples.<br>
`np.random(size=None)`

In [3]:
np.random.random(3)

array([0.87190516, 0.80779787, 0.58158015])

### 7. Logspace
Generate evenly spaced numbers on a log scale.<br>
`np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`

**Important params**<br>
`start`: starting value of the sequence.<br>
`end`: last value of the sequence.<br>
`endpoint`: if True, the last sample will be included in the sequence.<br>
`base`: The base of the log space. default is 10.

In [4]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

### 8. Array of zero
np.zeroes function helps to create an array of 0<br>
`np.zero(shape, dtype=float, order='C')`

**Important params**<br>
`shape`: shape of the resultant array.<br>
`dtype`: desired data type of resultant array. ‘int’ or default ‘float’

In [5]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 9. Array of Ones
np.ones function helps to create an array of 1.<br>
`np.ones(shape, dtype=None, order='C')`

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 10. Array of k Random Value
Creates an n-dimensional array of a random value.<br>
`np.full(shape, fill_value, dtype=None)<br>

**Important params**<br>
`fill_value`: Random value to fill inside the array.

In [8]:
np.full((2,4), fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### 11. Identity
Create an identity matrix with specified dimensions.<br>
`np.identity(n, dtype=None)`

In [9]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

## Array Operations

### 12. Min
Return the minimum value from the array.<br>
`np,min(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)`

**Important params**<br>
`axis`: axis along which to operate.<br>
`out`: alternative array to store the output.

In [2]:
arr = np.array([1,1,2,3,4,4,5,5,6,6,2,2])
np.min(arr)

np.int64(1)

### 13. Max
Return the maximum value from the array.<br>
`np.max(a, axis=None, out=None)`

In [12]:
np.max(arr)

np.int64(6)

### 14. Unique
Return an array with all the unique elements sorted.<br>
`np.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)`

**Important params**<br>
`return_index`: if True, return the indices of the array.<br>
`return_inverse`: if True, return the indices of the unique array.<br>
`return_counts`: if True, return the number of times each unique element appears inside the array.<br>
`axis`: The axis to operate on. By default, the array is considered flattened.

In [13]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 1, 2, 2, 2]))

### 15. Mean
It is used to get the mean of the array.<br>
`np.mean(a, axis=None, dtype=None, out=None)`

In [14]:
np.mean(arr, dtype='int')

np.int64(3)

### 16. Median
Return the median value of the array.<br>
`np.median(a, axis=None, out=None)`

In [15]:
arr =  np.array([[1,2,3],[5,8,4]])
np.median(arr)

np.float64(3.5)

### 17. Digitize
Return the indices of the bins to which each value in the input array belongs.<br>
`np.digitize(x, bins, right=False)`

**Important params**<br>
`bins`: Array of bins.<br>
`right`: Indicates whether the interval includes the right or left bin edge.

In [16]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.7])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4])

```
Exp        Value
x < 0     :   0
0 <= x <1 :   1
1 <= x <2 :   2
2 <= x <3 :   3
3 <=x     :   4
Compares -0.9 to 0, here x < 0 so Put 0 in resulting array.
Compares  0.5 to 0, here 0 <= x <1 so Put 1.
.
Compares 5.4 to 4, here 3<=x so Put 4
```

### 18. Reshape
It is one of the most used functions of NumPy. It Returns an array containing the same data with a new shape.<br>
`np.reshape(shape)`

In [17]:
A = np.random.randint(15, size=(4,3))
A

array([[ 4,  9,  2],
       [11,  1, 12],
       [ 1, 10,  7],
       [ 0, 14, 13]], dtype=int32)

In [18]:
A.reshape(3,4)

array([[ 4,  9,  2, 11],
       [ 1, 12,  1, 10],
       [ 7,  0, 14, 13]], dtype=int32)

In [19]:
A.reshape(-1)

array([ 4,  9,  2, 11,  1, 12,  1, 10,  7,  0, 14, 13], dtype=int32)

### 19. Expand Dimensions
It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model.<br>
`np.expand_dims(a, axis)`

In [20]:
arr = np.array([8, 14, 15, 1, 6, 11, 4, 9, 4, 12, 13, 13, 11])
np.expand_dims(arr, axis=0)

array([[ 8, 14, 15,  1,  6, 11,  4,  9,  4, 12, 13, 13, 11]])

In [21]:
np.expand_dims(arr, axis=1)

array([[ 8],
       [14],
       [15],
       [ 1],
       [ 6],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [12],
       [13],
       [13],
       [11]])

## 20. Squeeze
Reduce the dimension of an array by removing single-dimensional entrie.<br>
`np.squeeze(a, axis=None)`

In [22]:
arr = np.array([[8],[14],[1],[8],[11],[4],[9],[4],[1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

### 21. Count Non-Zero
Count all the non-zero elements and return their count.<br>
`np.count_nonzero(a, axis=None, *, keepdims=False)`

In [23]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

np.int64(3)

### 22. argwhere
Find and return all the indices of non-zero elements.<br>
`np.argwhere(a)`

In [24]:
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]])

### 23. argmax & argmin
argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems.<br>
`np.argmax(a, axis=None, out=None)`

In [25]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

np.int64(1)

argmin will return the index of the lowest element from the array.<br>
`np.argmin(a, axis=None, out=None)`

In [26]:
np.argmin(min)

np.int64(0)

### 24. Sort
Sort the array and return.<br>
`np.sort(a, axis=-1, kind=None, order=None)`

**Important params**<br>
`kind`: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}

In [27]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

### 25. Abs
Return the absolute values of elements inside an array. It is useful when an array contains negative values.

In [28]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

### 26. Round
Round the float values to a specified number of decimal points.<br>
`np.round(a, decimals=0, out=None)`

**Important params**<br>
`decimals`: Number of decimals point to keep.

In [29]:
a = np.random.random(size=(3,4))
a

array([[0.26372313, 0.25357741, 0.5360071 , 0.5506945 ],
       [0.00803329, 0.90254917, 0.43047451, 0.28412832],
       [0.65551841, 0.3901149 , 0.68704194, 0.53001627]])

In [31]:
np.round(a, decimals=0)

array([[0., 0., 1., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [32]:
np.round(a, decimals=1)

array([[0.3, 0.3, 0.5, 0.6],
       [0. , 0.9, 0.4, 0.3],
       [0.7, 0.4, 0.7, 0.5]])

### 27. Clip
It is used to keep the values of an array within a range.

In [33]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [34]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [35]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

---

## Replacing Values Inside Array

### 28. Where
Return elements from an array where a condition satisfies.<br>
`np.where(condition, [x,y])`

**Important params**<br>
`condition`: condition to match. if true yield xotherwise y.

In [36]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3]), array([0, 1, 2, 0, 1, 2]))

```
'''
[2][0] ᴇʟᴇᴍᴇɴᴛ (2ɴꜱ ʀᴏᴡ 0ᴛʜ ᴄᴏʟᴜᴍɴ) 6 > 5, ʀᴇᴛᴜʀɴ
[2][1] ᴇʟᴇᴍᴇɴᴛ (2ɴᴅ ʀᴏᴡ 1ꜱᴛ ᴄᴏʟᴜᴍɴ) 7 > 5, ʀᴇᴛᴜʀɴ
.
[3][2] ᴇʟᴇᴍᴇɴᴛ (3ᴅ ʀᴏᴡ 2ɴᴅ ᴄᴏʟᴜᴍɴ) 11 > 5, ʀᴇᴛᴜʀɴ
'''
```

In [38]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

It can also be used to replace elements inside the panda’s data frame.

`np.where(data[feature].isnull(), 1, 0)`

```
Replace Null Values with 1 and other as 0
```

### 29. Put
Replaces specified elements of an array with given values.<br>
`np.put(a, ind, v)`

**Important params**<br>
`a`: array<br>
`ind`: indices to be replaced.<br>
`v`: values to place.

In [41]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [40]:
np.put(arr, [1,2], [6,7])
arr

array([1, 6, 7, 4, 5, 6])

### 30. Copyto
Copy the content of one array into another.<br>
`copyto(dst, src, casting='same_kind', where=True)`

**Important params**<br>
`dst`: array into which values are copied.<br>
`src`: array from which values are copied.

In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr1)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [1 2 3]
After arr1 [4 5 6]
After arr2 [4 5 6]

## Set Operations

### 31. Retrieve Common Elements
`np.intersect1d` function returns all the unique values from both arrays in a sorted manner.<br>
`np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)`

**Important params**<br>
`assume_unique`: if true, then input arrays are both assumed to be unique.<br>
`return_indices`: if true, then common elements indices are returned.

In [3]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1, ar2)

array([1, 3, 4, 5])

In [4]:
np.intersect1d(ar1, ar2, return_indices=True)

(array([1, 3, 4, 5]), array([0, 2, 3, 4]), array([5, 0, 1, 2]))

array([0, 2, 3, 4], dtype=int64) :- Indices of common elements inside first array.<br>
array([5, 0, 1, 2], dtype=int64) :- Indices of common elements inside second array.

### 32. Difference
`np.setdiff1d` function returns all the unique elements from array 1 that are not present in arr2.

In [5]:
a = np.array([1,7,3,2,4,1])
b = np.array([9,2,5,6,7,8])
np.setdiff1d(a,b)

array([1, 3, 4])

### 33. Extracts Unique Elements From Both Arrays
`setxor1d` function will return all the unique values from both arrays in sorted order.

In [8]:
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

### 34. Union
`union1d` function will combine both arrays into one.

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

---

# Splitting

### 35. Horizontal Split
`hsplit` function will split the data horizontally into n equal parts.

In [4]:
A = np.array([[3, 4, 5, 2], [6, 7, 2, 6]])
np.hsplit(A,2) # splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [5]:
np.hsplit(A,4) # splits the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

### 36. Vertical Split
`vsplit` will split data vertically into n equal parts.

In [6]:
A = np.array([[3, 4, 5, 2], [6, 7, 2, 6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

---

# Stacking

### 37. Horizontal Stacking
`hstack` will stack appends one array at the end of another.

In [7]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

### 38. Vertical Stacking
`vstack` will stack one array on top of another.

In [8]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

---

# Comparing Two Arrays

### 39. allclose
`np.allclose` function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if the shape of both arrays is the same.

In [9]:
a = np.array([0.25, 0.4, 0.6, 0.32])
b = np.array([0.26, 0.3, 0.7, 0.32])
tolerance = 0.1   ## Total Difference
np.allclose(a,b,tolerance)

False

In [10]:
tolerance = 0.5
np.allclose(a,b,tolerance)

True

### Repeat
It is used to repeat elements of an array for n number of times.<br>
`np.repeat(a, repeats, axis=None)`

**Important params**<br>
`a`: element to repeat.<br>
`repeats`: number of times to repeat element.

In [11]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

Let's take a more pratical use case example, we have a dataset containing year-wise container quantity sales.

In [13]:
import pandas as pd
fruits = pd.DataFrame([
['Mango', 40],
['Apple', 90],
['Banana', 130]
], columns=['Product', 'ContainerSales'])
fruits

  Product  ContainerSales
0   Mango              40
1   Apple              90
2  Banana             130

In the dataset, the year column is missing. Let's try to add it using numpy.

In [14]:
fruits['year'] = np.repeat(2020, fruits.shape[0])
'''
Above code will repeat the year 2020 n times, where n is the leangth of data.
'''
fruits

  Product  ContainerSales  year
0   Mango              40  2020
1   Apple              90  2020
2  Banana             130  2020

### 41. tile
Construct an array by repeating A the number of times given by reps.<br>
`np.tile(A, reps)`

In [15]:
np.tile("Ram", 5)

array(['Ram', 'Ram', 'Ram', 'Ram', 'Ram'], dtype='<U3')

In [16]:
np.tile(3,(2,3))

array([[3, 3, 3],
       [3, 3, 3]])

---

# Einstein Summation Conventions

## 42. Einsum
This function is used to compute many multi-dimensional and linear algebraic operations on arrays.

In [17]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)

## EXTRACTS DIAGONALS
np.einsum('ii->i', a)

array([1, 5, 9])

In [18]:
## TRANSPOSE
np.einsum('ji', a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
## MATRIX MULTIPLICATION
np.einsum('ij,jk',a,b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [21]:
## SUM OF DIAGONAL
np.einsum('ii', a)

np.int64(15)

---

# Statistiacl Analysis

### 43. Histogram
It is an important statistical analysis function of NuPy that computes histogram values for a set of data.

In [22]:
A = np.array([[3, 4, 5, 2],
              [6, 7, 2,6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

### 44. Percentile
It computes the q-th percentile of the data along a specified axis.<br>
`np.percentile(a,q, axis=None, overwrite_input=False, interpolation='linear',keepdims=False)`

**Important params**<br>
`a`: array like input.<br>
`q`: percentile to compute.<br>
`overwrite_input`: if true, then allow the input array to modify the intermediate calculation to save memory.

In [23]:
a = np.array([[2, 4, 6], [4, 8, 12]])
np.percentile(a, 50)

np.float64(5.0)

In [24]:
np.percentile(a, 10)

np.float64(3.0)

In [25]:
arr = np.array([2,3,4,5,1,6])
np.percentile(a,5)

np.float64(2.5)

### 45. Standard Deviation and Variance
std and var are two functions of NumPy that calculates standard deviation and variance along an axis.

In [26]:
a = np.array([[2,4,6], [4,8,12]])

In [27]:
np.std(a, axis=1) ## Row Wise

array([1.63299316, 3.26598632])

In [28]:
np.std(a, axis=0) ## Column Wise

array([1., 2., 3.])

In [29]:
np.var(a, axis=1)

array([ 2.66666667, 10.66666667])

In [30]:
np.var(a,axis=0)

array([1., 4., 9.])

---

# Array Printing Options

### 46. Show Floats With Two Decimal Values

In [31]:
np.set_printoptions(precision=2)
a = np.array([12.23456, 32.34535])
print(a)

[12.23 32.35]

### 47. Prints Array To Its Max

In [32]:
np.set_printoptions(threshold=np.inf)

### 48. Increase The Number of Elements In Line

In [33]:
np.set_printoptions(linewidth=100)  ## Default 75

---

# Save and Load Array Data

### 49. Save
`savetxt` used to save the content of an array inside a text file.

In [36]:
''' Generate array with 500 elements '''

arr = np.linspace(10,100,500).reshape(25,20) 

## Saves Array Data Inside a txt File
np.savetxt('array.txt',arr)

### 50. Load
`loadtxt` used to load the content of an array from a text file. It takes the file name as a parameter.

In [35]:
### Loads Array Data From a txt File
np.loadtxt('array.txt')

array([[ 10.  ,  10.18,  10.36,  10.54,  10.72,  10.9 ,  11.08,  11.26,  11.44,  11.62,  11.8 ,
         11.98,  12.16,  12.34,  12.53,  12.71,  12.89,  13.07,  13.25,  13.43],
       [ 13.61,  13.79,  13.97,  14.15,  14.33,  14.51,  14.69,  14.87,  15.05,  15.23,  15.41,
         15.59,  15.77,  15.95,  16.13,  16.31,  16.49,  16.67,  16.85,  17.03],
       [ 17.21,  17.39,  17.58,  17.76,  17.94,  18.12,  18.3 ,  18.48,  18.66,  18.84,  19.02,
         19.2 ,  19.38,  19.56,  19.74,  19.92,  20.1 ,  20.28,  20.46,  20.64],
       [ 20.82,  21.  ,  21.18,  21.36,  21.54,  21.72,  21.9 ,  22.08,  22.26,  22.44,  22.63,
         22.81,  22.99,  23.17,  23.35,  23.53,  23.71,  23.89,  24.07,  24.25],
       [ 24.43,  24.61,  24.79,  24.97,  25.15,  25.33,  25.51,  25.69,  25.87,  26.05,  26.23,
         26.41,  26.59,  26.77,  26.95,  27.13,  27.31,  27.49,  27.68,  27.86],
       [ 28.04,  28.22,  28.4 ,  28.58,  28.76,  28.94,  29.12,  29.3 ,  29.48,  29.66,  29.84,
         30.02,  30.2 ,  30.38,  30.56,  30.74,  30.92,  31.1 ,  31.28,  31.46],
       [ 31.64,  31.82,  32.  ,  32.18,  32.36,  32.55,  32.73,  32.91,  33.09,  33.27,  33.45,
         33.63,  33.81,  33.99,  34.17,  34.35,  34.53,  34.71,  34.89,  35.07],
       [ 35.25,  35.43,  35.61,  35.79,  35.97,  36.15,  36.33,  36.51,  36.69,  36.87,  37.05,
         37.23,  37.41,  37.6 ,  37.78,  37.96,  38.14,  38.32,  38.5 ,  38.68],
       [ 38.86,  39.04,  39.22,  39.4 ,  39.58,  39.76,  39.94,  40.12,  40.3 ,  40.48,  40.66,
         40.84,  41.02,  41.2 ,  41.38,  41.56,  41.74,  41.92,  42.1 ,  42.28],
       [ 42.46,  42.65,  42.83,  43.01,  43.19,  43.37,  43.55,  43.73,  43.91,  44.09,  44.27,
         44.45,  44.63,  44.81,  44.99,  45.17,  45.35,  45.53,  45.71,  45.89],
       [ 46.07,  46.25,  46.43,  46.61,  46.79,  46.97,  47.15,  47.33,  47.52,  47.7 ,  47.88,
         48.06,  48.24,  48.42,  48.6 ,  48.78,  48.96,  49.14,  49.32,  49.5 ],
       [ 49.68,  49.86,  50.04,  50.22,  50.4 ,  50.58,  50.76,  50.94,  51.12,  51.3 ,  51.48,
         51.66,  51.84,  52.02,  52.2 ,  52.38,  52.57,  52.75,  52.93,  53.11],
       [ 53.29,  53.47,  53.65,  53.83,  54.01,  54.19,  54.37,  54.55,  54.73,  54.91,  55.09,
         55.27,  55.45,  55.63,  55.81,  55.99,  56.17,  56.35,  56.53,  56.71],
       [ 56.89,  57.07,  57.25,  57.43,  57.62,  57.8 ,  57.98,  58.16,  58.34,  58.52,  58.7 ,
         58.88,  59.06,  59.24,  59.42,  59.6 ,  59.78,  59.96,  60.14,  60.32],
       [ 60.5 ,  60.68,  60.86,  61.04,  61.22,  61.4 ,  61.58,  61.76,  61.94,  62.12,  62.3 ,
         62.48,  62.67,  62.85,  63.03,  63.21,  63.39,  63.57,  63.75,  63.93],
       [ 64.11,  64.29,  64.47,  64.65,  64.83,  65.01,  65.19,  65.37,  65.55,  65.73,  65.91,
         66.09,  66.27,  66.45,  66.63,  66.81,  66.99,  67.17,  67.35,  67.54],
       [ 67.72,  67.9 ,  68.08,  68.26,  68.44,  68.62,  68.8 ,  68.98,  69.16,  69.34,  69.52,
         69.7 ,  69.88,  70.06,  70.24,  70.42,  70.6 ,  70.78,  70.96,  71.14],
       [ 71.32,  71.5 ,  71.68,  71.86,  72.04,  72.22,  72.4 ,  72.59,  72.77,  72.95,  73.13,
         73.31,  73.49,  73.67,  73.85,  74.03,  74.21,  74.39,  74.57,  74.75],
       [ 74.93,  75.11,  75.29,  75.47,  75.65,  75.83,  76.01,  76.19,  76.37,  76.55,  76.73,
         76.91,  77.09,  77.27,  77.45,  77.64,  77.82,  78.  ,  78.18,  78.36],
       [ 78.54,  78.72,  78.9 ,  79.08,  79.26,  79.44,  79.62,  79.8 ,  79.98,  80.16,  80.34,
         80.52,  80.7 ,  80.88,  81.06,  81.24,  81.42,  81.6 ,  81.78,  81.96],
       [ 82.14,  82.32,  82.51,  82.69,  82.87,  83.05,  83.23,  83.41,  83.59,  83.77,  83.95,
         84.13,  84.31,  84.49,  84.67,  84.85,  85.03,  85.21,  85.39,  85.57],
       [ 85.75,  85.93,  86.11,  86.29,  86.47,  86.65,  86.83,  87.01,  87.19,  87.37,  87.56,
         87.74,  87.92,  88.1 ,  88.28,  88.46,  88.64,  88.82,  89.  ,  89.18],
       [ 89.36,  89.54,  89.72,  89.9 ,  90.08,  90.26,  90.44,  90.62,  90.8 ,  90.98,  91.16,
         91.34,  91.52,  91.7 ,  91.88,  92.06,  92.24,  92.42,  92.61,  92.79],
       [ 92.97,  93.15,  93.33,  93.51,  93.69,  93.87,  94.05,  94.23,  94.41,  94.59,  94.77,
         94.95,  95.13,  95.31,  95.49,  95.67,  95.85,  96.03,  96.21,  96.39],
       [ 96.57,  96.75,  96.93,  97.11,  97.29,  97.47,  97.66,  97.84,  98.02,  98.2 ,  98.38,
         98.56,  98.74,  98.92,  99.1 ,  99.28,  99.46,  99.64,  99.82, 100.  ]])